version: '3.3'

services:
  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=YourStore
      - POSTGRES_USER=jzlbornoz
      - POSTGRES_PASSWORD=fatima17
    ports:
      -5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_MAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80

